### ISSUE TITLE
Varying Dollar Bills

### ISSUE THREAD

**Issue by pieetrr** [Alziibun/Perdition#11]
For the economy to even start resembling something viable we need to make different dollar bills so people can actually carry their money around and use it. It's fine if they need to break it all down to 1 dollar bills to buy things from the vending machines *for now*, the main issue that needs tackling is carrying and storing the money, we will make this more complex later on. Baby steps.

- [x] 10000 dollar bill
- [x] 1000 dollar bill
- [x] 100 dollar bill
- [x] 50 dollar bill
- [x] 20 dollar bill
- [x] 10 dollar bill

**Comment by Alziibun** [comment]
Recipes also register on the context menu (right clicking something) so all you really need to do is add recipes for each of these.  You can make a new file if you want

**Comment by pieetrr** [comment]
yes im aware, i guess you need to make the bills first as new items but then it should be very straight forward with the actual recipes. I will give it a go probably tomorrow

**Comment by Alziibun** [comment]
You can make a checklist with ` - [ ] ` as the markdown

Like so
`- [ ] unchecked item`
`- [x] checked item`

**Comment by TheQuaccer** [comment]
All Added, Any changed which need to be made contact me.

**Comment by Alziibun** [comment]
### Recipes
- [x]  10000 dollar bill
- [x]  1000 dollar bill
- [x]  100 dollar bill
- [x]  50 dollar bill
- [x]  20 dollar bill
- [x]  10 dollar bill
