### ISSUE TITLE
`Tooltip` requires a reference to a translation file, not a string

### ISSUE THREAD

**Issue by Alziibun** [Alziibun/Perdition#22]
https://github.com/PerditionPvE/Perdition/blob/bf5c03c1d18180a7cfd14d6d7d222e158908a594/media/scripts/Perdition_items.txt#L640
https://github.com/PerditionPvE/Perdition/blob/bf5c03c1d18180a7cfd14d6d7d222e158908a594/media/scripts/Perdition_items.txt#L651
https://github.com/PerditionPvE/Perdition/blob/bf5c03c1d18180a7cfd14d6d7d222e158908a594/media/scripts/Perdition_items.txt#L662
https://github.com/PerditionPvE/Perdition/blob/bf5c03c1d18180a7cfd14d6d7d222e158908a594/media/scripts/Perdition_items.txt#L673
https://github.com/PerditionPvE/Perdition/blob/bf5c03c1d18180a7cfd14d6d7d222e158908a594/media/scripts/Perdition_items.txt#L684

>Tooltip = Tooltip_UseOnHealthPanel,
>Will display tooltip if item is moused over in inventory, requires Translation file that defines the text to display.

@TheQuaccer

**Comment by TheQuaccer** [comment]
Removed the tooltips due to it not being needed
