### ISSUE TITLE
Rework dollars over $100 into "cheques"

### ISSUE THREAD

**Issue by Alziibun** [Alziibun/Perdition#32]
To make #11 less silly

- [ ] "small" cheque ($5,000 max)
- [ ] "medium" cheque ($500,000 max)
- [ ] "large" cheque ($1,000,000 max)
- [ ] Give cheques dynamic names based on how much money remains

**Comment by pieetrr** [comment]
To be honest i find this uneccesary but might be cool and give some more flavour so why not.
500k is ridiculous unless we are inflating like its 2022. Maybe 5k < 10k < 50k?
However i'll put forth that cheques being drainable is kinda off. You redeem cheques, its a one time conversion. Maybe we can introduce a debit or prepaid card system? Differing cards having differing maxs of how much money they can fit, you can only drain money when you are near ATMs? I don't mind if you keep the drainable cheques but this sounds better for me.

**Comment by HaleChristopher** [comment]
What about a drainable credit card for $5000 and a gold credit card for $20000?

**Comment by Alziibun** [comment]
I have added new bills in the economy branch that are still legal to this day but are no longer made
