### ISSUE TITLE
Uhhh make the recipe to create sacks of vegetables

### ISSUE THREAD

**Issue by seishedaye** [Alziibun/Perdition#34]
You know, the ones that spawn in stores that you can open to reveal 12 of a crop, but in reverse

**Comment by seishedaye** [comment]
make it utilize the farming and tailoring skills, maybe level 2 of each

**Comment by TheQuaccer** [comment]
- [x] Onion Sack
- [x] Corn Sack
- [x] Leek Sack
- [x] Carrot Sack
- [x] Strawberry Sack
- [x] Tomato Sack
- [x] Radish Sack
- [x] Broccololian Sack
- [x] Cabbage sack
- [x] Lettuce Sack
Sacks should equal up to 3kg(15 Lettuce in a sack)
- [x] Recipe for empty Sack

**Comment by pieetrr** [comment]
Recipe for empty Sack should need tailoring 2. 
I don't see why putting farm product in a sack needs farming skill requirement.

**Comment by Alziibun** [comment]
> Recipe for empty Sack should need tailoring 2.
> I don't see why putting farm product in a sack needs farming skill requirement.

probably becuase the mod for it required farming 1 lmao

**Comment by TheQuaccer** [comment]
Also for anyone wanting to help its Broccoli not Broccololian. im just shit as spelling.

**Comment by TheQuaccer** [comment]
> Recipe for empty Sack should need tailoring 2. I don't see why putting farm product in a sack needs farming skill requirement.

this stuff should not use any experience.. ITS PUTTING VEGETABLES INSIDE A SACK!. YOU DONT NEED EXPERIENCE TO PUT SOMETHING INSIDE A BAG. *ahem*
this will also not give nay experience to not be able to farm experience like planks stacking.

**Comment by TheQuaccer** [comment]
> this stuff should not use any experience.. ITS PUTTING VEGETABLES INSIDE A SACK!. YOU DONT NEED EXPERIENCE TO PUT SOMETHING INSIDE A BAG. _ahem_ this will also not give nay experience to not be able to farm experience like planks stacking.

disregard this. brain fart.. lil crazy quacc decided to speak.

**Comment by seishedaye** [comment]
ok cool that's one opinion but also make it use tailoring and farming because you have to have knowledge of how to sew the bag shut and... something about handling vegetables

**Comment by TheQuaccer** [comment]
> ok cool that's one opinion but also make it use tailoring and farming because you have to have knowledge of how to sew the bag shut and... something about handling vegetables

or you know.. you can just tie it off with a rope... and no farming skills will not be used for this

**Comment by pieetrr** [comment]
> ok cool that's one opinion but also make it use tailoring and farming because you have to have knowledge of how to sew the bag shut and... something about handling vegetables

Creating the sack should need some tailoring. Producing the farming product needs some farming. Placing the product into the sack shouldnt require anything.

**Comment by TheQuaccer** [comment]
Added all items, Tailoring is the only skill that will be used cus you don't need farming skill to put stuff in bags.
