### ISSUE TITLE
Carpentry Update

### ISSUE THREAD

**Issue by seishedaye** [Alziibun/Perdition#49]
I know we're planning to remove the stupid better building mod, but what we can do instead is add recipes based off of the carpentry skill to be able to make new furnitures too. Like pretty couches and... windows and whatnot. I don't wanna write out a whole thing, discuss amongst yourselves on this one for rn

**Comment by Alziibun** [comment]
It is planned in #12 as a carpenter specialty trait.  A system will be added where specialized carpenters can write blueprints from furniture they find in the world and it creates a recipe manual from that.
