### ISSUE TITLE
Server ATM patch

### ISSUE THREAD

**Issue by Alziibun** [Alziibun/Perdition#57]
From impasta alzii

If we keep the vending machine mod then we should remove all recipes except the following.
If we make our own then these are the recipes that i want.
Some recipes are purposefully on the pricey side cause raiding the map should be the player's main way of getting things, then crafting things and then finally buy things they can't bother looting or crafting. There are a few exclusions to that rule, i.e. ammunition is fairly priced.

**Weapon Vendor**
- [x] Katana - 1500$
- [x] Machete - 1000$
- [x] Fireaxe - 1000$
- [x] Hunting Knife - 500$
- [x] 5.56 ammo box - 150$
- [x] 12g ammo box - 200$
- [x] .45 ammo box - 150$
- [x] .9mm ammo box - 150$
- [x] 7.62x39 ammo box - 200$
- [x] 7.62x51 ammo box - 200$
- [x] .44 ammo box - 150$
- [x] .44-40 WCF ammo box - 150$
- [x] .38 ammo box - 150$
- [x] .357 ammo box - 150$
- [x] .223 ammo box - 150$
- [x] .308 ammo box - 150$
- [x] .22LR ammo box -150$
- [x] .30-06 ammo box - 150$
- [x] 22Silencer - 3000$
- [x] 9mmSilencer - 3000$
- [x] .45Silencer - 2500$
- [x] .38Silencer - 2500$
- [x] 223Silencer - 2500$
- [x] 308Silencer - 2500$
- [x] ShotgunSilencer - 3000$
- [x] DoubleBarrelShotgun - 1200$

The only firearm for sale will be the doublebarrel, if people want the gucci stuff they need to find said gucci stuff. Firearms should feel better as loot. No mags, no attachments other than silencers.  **_Posted by the "Make firearms great again" gang._**
Silencers are to be removed from the world loot distribution unless we can find a way to make them more extremely rare.

**Tool Vendor**
- [x] Crowbar - 800$
- [x] Woodaxe - 1000$
- [x] Pickaxe - 800$
- [x] Propane Tank - 500$
- [x] Welder Mask - 500$
- [x] Propane Torch - 500$
- [x] Jack - 400$
- [x] Tirepump - 400$
- [x] Lugwrench - 400$
- [x] Wrench - 300$
- [x] Screwdriver - 300$
- [x] Battery Charger - 700$ 
- [x] Box of Nails - 250$
- [x] Box of Screws - 200$
- [x] Fishing Rod - 200$

Tried to be pricey as in you'd buy most of the tools here as a last resort if you cant find them anywhere else.

**Food Vendor**
- [x] Can Opener - 100$
- [x] Milk - 50$
- [x] Pasta - 50$
- [x] Rice - 50$
- [x] Salt - 20$
- [x] Pepper - 20$
- [x] Vegetable Oil - 80$
- [x] Olive Oil - 100$
- [x] Sugar - 200$
- [x] Brown Sugar - 200$
- [x] Water Bottle - 20$
- [x] Yeast - 100$

Tried to include basic stuff, stuff that actually feels like food and that you cant farm and also stuff that will be probably used in the future for crafting.

**Vehicle Part Vendor**
- [x] Spare Engine Part - 100$
- [x] Towbar - 500$
- [x] RunFlat Tire - 1000$
- [x] Standard Hood - 500$
- [x] Heavy Hood - 700$
- [x] Sports Hood - 1000$
- [x] Standard Windshield - 350$
- [x] Heavy Windshield - 450$
- [x] Sports Windshield - 600$
- [x] w900 bullbar - 1000$

**Book Vendor** (if we just keep the old mod then the books should go in the Tool Vendor. Else we will place this new Book Vendor in a few big libraries around the map.

- [x] Lv 1 Books for [Strength/Fitness/Nimble/Axe/LongBlunt/ShortBlunt/LongBlade/ShortBlade/Spear/Maintenance] at 2000$
- [x] Lv 2 Books for [Strength/Fitness/Nimble/Axe/LongBlunt/ShortBlunt/LongBlade/ShortBlade/Spear/Maintenance] at 2250$
- [x] Lv 3 Books for [Strength/Fitness/Nimble/Axe/LongBlunt/ShortBlunt/LongBlade/ShortBlade/Spear/Maintenance] at 2500$
- [x] Lv 4 Books for [Strength/Fitness/Nimble/Axe/LongBlunt/ShortBlunt/LongBlade/ShortBlade/Spear/Maintenance] at 2750$
- [x] Lv 5 Books for [Strength/Fitness/Nimble/Axe/LongBlunt/ShortBlunt/LongBlade/ShortBlade/Spear/Maintenance] at 3000$

**Sellable Items** (ideas welcome)

- [x] Wallets for 30$
- [x] Credit cards for 200$
- [x] Jewelry for 3$
- [x] Watches for 3$
- [x] Metal Scraps for 2$
- [x] Electronic Scraps for 2$
- [x] Gunpowder for 2$
- [x] Sleeping Tablets/Vitamins/Painkillers/Betablockers for 10$

**Comment by Alziibun** [comment]
> Also the black books need to be removed from the loot pools and added as recipes in the vending machines. 
> For now lets put them in the tools vending machine. Let's go with 2500 dollars per book.

Since the Extra Books mod just adds books is using very vanilla methods we can quickly make our own and just ignore the pains of patching it

**Comment by TheQuaccer** [comment]
yeah, i was gonna say you can just remove the distrubution files of the mod but forgot.

**Comment by Alziibun** [comment]
> yeah, i was gonna say you can just remove the distrubution files of the mod but forgot.

not as a third party patch

**Comment by Alziibun** [comment]
The code for the ATMs are in spanish, please give me the details and I will edit them accordingly

**Comment by pieetrr** [comment]
wow look at you go alzii nice list

**Comment by Alziibun** [comment]
wow pietr nice list
