### ISSUE TITLE
Canned Electron Boogaloo Ep.1 | Batteries

### ISSUE THREAD

**Issue by TheQuaccer** [Alziibun/Perdition#80]
Improvements to the battery system and adds Battery Rechargeability and Battery Packs. Made to solve the problem of short lasting batteries without Increasing lifespan by 20000 Times.

###
- Pack O' Batteries 4/6/12
- Ham Radio Wall Adapter (Way to make Ham Radios Use power from generator)
- Batteries have a Recharge limit. limiting the amount of times batteries can be recharged.
- Better Battery Icon/Texture
### Battery Charger
Adds a way to recharge Multiple Batteries. Each recgarge takes off 1 Recharge limit and takes power when turned on. simular to the car battery charger but lower powered and can charge multiple small batteries

TODO LIST

- [x] Pack Of Batteries 4
- [x] Pack Of Batteries 8
- [x] Pack Of Batteries 12
- [x] Pack Of Batteries 16
- [ ] Add all Packs to distribution list
- [ ] Battery Recharge Limit
- [x] Wall adapter
- [x] Battery Charger

**Comment by Alziibun** [comment]
Looks fine, and I'm pretty sure there is vanilla code for ham radios using generator power

**Comment by TheQuaccer** [comment]
@Alziibun can you make the code for the recharge limit, Wall adapter and the charger?

**Comment by Alziibun** [comment]
Why not try it yourself?  I still have a lot to do with shops right now

**Comment by TheQuaccer** [comment]
> Why not try it yourself? I still have a lot to do with shops right now

will try and suffer, but if you have time pls help

**Comment by Alziibun** [comment]
I will answer questions you have, time to fly the nest little one

**Comment by TheQuaccer** [comment]
> I will answer questions you have, time to fly the nest little one

Im a pond duck, I cant fly ;-;

**Comment by Alziibun** [comment]
Don't drown!

**Comment by TheQuaccer** [comment]
IM A DUCK! WE CANT DROWN!!

**Comment by Alziibun** [comment]
Are you struggling with the last 2?
