### ISSUE TITLE
Vomit function

### ISSUE THREAD

**Issue by seishedaye** [Alziibun/Perdition#82]
Idea to create a vomit feature that lets you drain your queasiness back to 0 (for the sole purpose of when like you're in a hard to leave area surrounded by corpses and cant get to a safe place with fresh air)

It could also make you moderately hungry and be unusable if you ARE hungry

When I'm nauseous, throwing up always makes me feel better.

**Comment by TheQuaccer** [comment]
Good idea but.. why...

**Comment by Alziibun** [comment]
Let's leave the viscera out of the server
